import Chat from "@/components/Chat";

// The page reads as a real product page. The chat is a single component
// dropped into an otherwise ordinary Next.js page — that is the selling point.

const PIPELINE: { step: string; detail: string }[] = [
  { step: "Ingest", detail: "load the docs" },
  { step: "Chunk", detail: "~600 tok, 80 overlap" },
  { step: "Embed", detail: "OpenAI embeddings" },
  { step: "Retrieve", detail: "cosine top-k" },
  { step: "Ground + generate", detail: "Claude, native citations" },
  { step: "Stream", detail: "tokens live" },
  { step: "Cite", detail: "click → source" },
];

export default function Page() {
  return (
    <main className="page">
      <div className="pageInner">
        <header className="hero">
          <span className="badge">
            <span className="badgeDot" aria-hidden />
            RAG demo · grounded &amp; cited
          </span>
          <h1 className="title">Chat with your docs</h1>
          <p className="subtitle">
            Ask questions, get answers grounded in the docs — with clickable
            citations.
          </p>
        </header>

        <Chat />

        <section className="how" aria-label="How it works">
          <h2 className="howTitle">How it works</h2>
          <p className="howLead">
            Everything below the chat is a normal Next.js page. The assistant is
            one self-contained React component, backed by a small retrieval +
            generation pipeline:
          </p>

          <ol className="pipeline">
            {PIPELINE.map((p, i) => (
              <li className="pstep" key={p.step}>
                <span className="pnum">{i + 1}</span>
                <span className="pbody">
                  <span className="pname">{p.step}</span>
                  <span className="pdetail">{p.detail}</span>
                </span>
              </li>
            ))}
          </ol>

          <p className="howNote">
            The corpus is fixed and pre-embedded into a small JSON index, so
            retrieval is a sub-millisecond cosine scan in a serverless route —
            no vector database, no extra services. Answers are generated by
            Claude with <strong>native citations</strong>: every claim links
            back to the exact source passage, and questions outside the docs are
            answered honestly instead of being made up.
          </p>
        </section>

        <footer className="foot">
          <span>Next.js 15 · React · Anthropic Claude · OpenAI embeddings</span>
          <span className="footSep" aria-hidden>
            ·
          </span>
          <span>Deployed serverless on Vercel</span>
        </footer>
      </div>
    </main>
  );
}
