import type { ComponentType } from "react";
import {
  MessagesSquare,
  FileInput,
  Scissors,
  Binary,
  Search,
  Sparkles,
  Radio,
  Quote,
} from "lucide-react";
import Chat from "@/components/Chat";

// The page reads as a real product page. The chat is a single component
// dropped into an otherwise ordinary Next.js page — that is the selling point.

type IconType = ComponentType<{ size?: number; strokeWidth?: number }>;

const PIPELINE: { step: string; detail: string; Icon: IconType }[] = [
  { step: "Ingest", detail: "load the docs", Icon: FileInput },
  { step: "Chunk", detail: "~600 tok, 80 overlap", Icon: Scissors },
  { step: "Embed", detail: "Gemini embeddings", Icon: Binary },
  { step: "Retrieve", detail: "cosine top-k", Icon: Search },
  { step: "Ground + generate", detail: "OpenRouter, cited [n]", Icon: Sparkles },
  { step: "Stream", detail: "tokens live", Icon: Radio },
  { step: "Cite", detail: "click a citation to open its source", Icon: Quote },
];

export default function Page() {
  return (
    <main className="page">
      <div className="pageInner">
        <nav className="siteNav" aria-label="Primary">
          <div className="nav-glass navInner">
            <span className="navIcon" aria-hidden>
              <MessagesSquare size={18} strokeWidth={1.8} />
            </span>
            <span className="navName">Docs assistant</span>
            <span className="navTag">grounded RAG demo</span>
          </div>
        </nav>

        <header className="hero">
          <h1 className="title">Chat with your docs</h1>
          <p className="subtitle">
            Ask questions and get answers grounded in the docs, with clickable
            citations.
          </p>
        </header>

        <Chat />

        <section className="how" aria-label="How it works">
          <div className="list-header">How it works</div>
          <p className="howLead">
            Everything below the chat is a normal Next.js page. The assistant is
            one self-contained React component, backed by a small retrieval +
            generation pipeline:
          </p>

          <ol className="list-inset pipeline">
            {PIPELINE.map((p, i) => (
              <li className="list-row" key={p.step}>
                <span className="pstepIcon" aria-hidden>
                  <p.Icon size={17} strokeWidth={1.8} />
                </span>
                <span className="pbody">
                  <span className="pname">{p.step}</span>
                  <span className="pdetail">{p.detail}</span>
                </span>
                <span className="pnum" aria-hidden>
                  {i + 1}
                </span>
              </li>
            ))}
          </ol>

          <p className="howNote">
            The corpus is fixed and pre-embedded into a small JSON index, so
            retrieval is a sub-millisecond cosine scan in a serverless route,
            with no vector database and no extra services. Answers are generated by a
            free model with <strong>inline citations</strong>: every claim links
            back to the source passage it came from, and questions outside the
            docs are answered honestly instead of being made up.
          </p>
        </section>

        <footer className="foot">
          <span>Next.js 16 · React 19 · OpenRouter (free) · Gemini embeddings</span>
          <span className="footSep" aria-hidden>
            ·
          </span>
          <span>Deployed serverless on Vercel</span>
        </footer>
      </div>
    </main>
  );
}
